services:
  # PostgreSQL with pgvector extension
  postgres:
    image: pgvector/pgvector:pg16
    container_name: relevantic_postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME:-relevantic_recall}
      POSTGRES_USER: ${DB_USER:-relevantic_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-relevantic_password}
      PGPASSWORD: ${DB_PASSWORD:-relevantic_password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - relevantic_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-relevantic_user} -d ${DB_NAME:-relevantic_recall}"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Neo4j Graph Database
  neo4j:
    image: neo4j:5.15
    container_name: relevantic_neo4j
    env_file:
      - .env
    environment:
      NEO4J_AUTH: ${NEO4J_USER:-neo4j}/${NEO4J_PASSWORD:-relevantic_password}
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
      NEO4J_dbms_security_procedures_allowlist: apoc.*

    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    networks:
      - relevantic_network
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u ${NEO4J_USER:-neo4j} -p ${NEO4J_PASSWORD:-relevantic_password} 'RETURN 1'"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Relevantic Recall Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: relevantic_app
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://${DB_USER:-relevantic_user}:${DB_PASSWORD:-relevantic_password}@postgres:5432/${DB_NAME:-relevantic_recall}
      - SYNC_DATABASE_URL=postgresql://${DB_USER:-relevantic_user}:${DB_PASSWORD:-relevantic_password}@postgres:5432/${DB_NAME:-relevantic_recall}
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=${NEO4J_USER:-neo4j}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD:-relevantic_password}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
      - DEBUG=true
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      neo4j:
        condition: service_healthy
    networks:
      - relevantic_network
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

volumes:
  postgres_data:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:

networks:
  relevantic_network:
    driver: bridge
